### ISSUE TITLE
data structure for receiving marking scheme from server

### ISSUE THREAD

**Issue by martinmphil** [martinmphil/judgement_tests#12]
​With respect to establishing a marking scheme containing ideal answers, could the back-end supply each exam with a marking scheme in the following format?

```javascript
const markingScheme = {
examId: 1,
correctAnswers: [
  { Q: 1, best: 1, worst: 4 },

  { Q: 2, best: 3, worst: 2 },

  { Q: 3, best: 4, worst: 1 },

  { Q: 4, best: 2, worst: 4 }
]
};
```

In some circumstances Becky might need to pose scenarios that score only best or only worst options, not both. Under these conditions, I'd like to request that we set best=0 or worst=0 as appropriate in the idealAnswer object that we'll fetch from the server for that exam.

Fitting in with this pattern, can the back-end label the correct answers as either 1, 2, 3 or 4 for a, b, c, or d options?

**Comment by lanroth** [comment]
I would suggest simply not supplying `best` or `worst` in the case where there isn't one. Using `0` as a magic number is an anti-pattern.

The marking scheme is already available from here, though it also returns data you might not need.
https://example.com/sjt-backend/exams/1

Rather than add another endpoint I think we should use the one we've got at this stage.

best/worst are zero indexed. ie between 0 and 3 inclusive. I think it's normally better to use zero indexing until it is presented in the UI.

**Comment by martinmphil** [comment]
Brilliant, thanks for clarifying that the server should respond to a scenario with only one scoring criteria by only returning either a best key-value or a worst key-value. I will try changing the frontend code to detect the presence or absence of these values before proceeding with the marking. 

With regard to retrieving a marking scheme from the server, I must be missing something because I only see scenario text in my response to 
/sjt-backend/exams/1

**Comment by lanroth** [comment]
You are of course completely correct. I removed the best/worst from that endpoint last week and was looking at stale data. Doh!

What I might do is make returning best/worst conditional on the user being an author.

**Comment by lanroth** [comment]
I've added a parameter `withScoring`. It'll need securing before we go live, but for now it means you can get the scoring again.

e.g. https://example.com/sjt-backend/exams/1?withScoring=true

**Comment by martinmphil** [comment]
Splendid looking swagger, cheers. I'll try fetching from /sjt-backend/exams/1?withScoring=true

**Comment by lanroth** [comment]
The swagger is incorrect - `withScoring` is optional and defaults to false.

**Comment by martinmphil** [comment]
On swagger, I used the "Try it out" button and supplied withScoring as true and received data containing worst and best values.

**Comment by martinmphil** [comment]
https://github.com/martinmphil/judgement_tests/issues/14#issue-574082689
supersedes this discussion with definition of rubric as the marking scheme.
