### ISSUE TITLE
Rubric and marking pile web app API

### ISSUE THREAD

**Issue by martinmphil** [martinmphil/judgement_tests#14]
To generate exam results for our Assessors, we currently GET data from
`sjt-backend/exams/${examId}?withScoring=true`
`sjt-backend/candidates/allanswers/${examId}`
see [Issue#10](https://github.com/martinmphil/judgement_tests/issues/10) and [Issue#12](https://github.com/martinmphil/judgement_tests/issues/12). 
TODO remove paramter: `?withScoring=true` 

Assessors enter an exam id to request candidate submissions.

We want the following two restful API endpoints:
Get rubric with ideal answer choices (as prescribed by the author),
`sjt-backend/exams/rubrics/${examId}`

Get candidates' submissions,
`sjt-backend/exams/submissions/${examId}`

A query requesting a rubric of ideal answers respond with an array like:
`[{ best: x1, worst: y1 }, { best:x2, worst: y2 }, ...]`
where x and y are either 0, 1, 2 or 3 for options a, b, c and d respectively?

The assessor page could also process candidate's submissions as an array like the following -
```
[
  {
    name: "",
    email: "",
    candidateId: 0,
    submission: [{ best: x, worst: y, timestamp: "", ip: "" }, ...]
  }, ...
]
```

**Comment by lanroth** [comment]
@martinmphil I think this is done, if so please close
