### ISSUE TITLE
Authors' web app API

### ISSUE THREAD

**Issue by martinmphil** [martinmphil/judgement_tests#15]
When an author creates a new exam how might they request a new `examId`?

Would we create the following restful API endpoint for authors? 
`sjt-backend/authors/${examId}/`

If so, is the following data structure appropriate to POST a series of scenario texts and ideal answers to the server, thus creating a new exam?

``` 
{
  exam_id: 101,
  exam_text: [
    {
      answersOptions: [
        "q1_opt_text_A",
        "q1_opt_text_B",
        "q1_opt_text_C",
        "q1_opt_text_D"
      ],
      ideally: { best: x1, worst: y1 },
      scenarioText: "q1_scenario_text"
    },
    {
      answersOptions: [
        "q2_opt_text_A,
        "q2_opt_text_B",
        "q2_opt_text_C",
        "q2_opt_text_D"
      ],
      ideally: { best: x2, worst: y2 }
      scenarioText: "q2_scenario_text"
    }
  ]
}
``` 
where x and y are either 1, 2, 3, or 4 for options a, b, c and d respectively. 

In this style the answer option order, and the question order, and the question number can be derived from their position in their respective arrays. 

Or perhaps we might build exams one question at a time,
eg POST the following to 
`sjt-backend/authors/${examId}/${questionNumber}/`
```
{
  answersOptions: [
    "q1_opt_text_A",
    "q1_opt_text_B",
    "q1_opt_text_C",
    "q1_opt_text_D"
  ],
  ideally: { best: x1, worst: y1 },
  scenarioText: "q1_scenario_text"
}
```

**Comment by lanroth** [comment]
> When an author creates a new exam how might they request a new examId?

It's normal to POST without an id and let the backend generate and return a new id

An endpoint should mirror the existing exam, e.g.
POST to http://example.com/sjt-backend/exam
and response contains the id, or alternatively the newly created exam with the id embedded.
