### ISSUE TITLE
get exams needs to be updated to reflect PUT/POST json structure

### ISSUE THREAD

**Issue by lanroth** [martinmphil/judgement_tests#19]
Update GET http://example.com/sjt-backend/exams/{examId} response
to be of the form described here:
https://github.com/martinmphil/judgement_tests/issues/18

**Comment by martinmphil** [comment]
The change described in this issue will probably require an update to `App.tsx`
https://github.com/martinmphil/judgement_tests/blob/4bc8a3c8b7de477712e7f41a828a8a1586c89148/src/App.tsx#L90-L91

**Comment by lanroth** [comment]
@martinmphil is this done? Close if so
