### ISSUE TITLE
Provide precise error messages

### ISSUE THREAD

**Issue by lanroth** [martinmphil/judgement_tests#21]
For example:

1. backend unavailable
2. candidate token not found
3. candidate name/email
4. exam not found
5. submission error as returned by server

**Comment by martinmphil** [comment]
Thanks for writing-up our verbal discussion. It's good to read the list we generated.

**Comment by martinmphil** [comment]
SJT candidate page now provides individual feedback messages to user for errors on examId, candidateId, examPaper, questionNumber, and candidateName, and submissionsError.
