### ISSUE TITLE
Make backend URL configurable in a single place

### ISSUE THREAD

**Issue by lanroth** [martinmphil/judgement_tests#22]
e.g.
```js
const BACKEND_BASE_URL="http://example.com/sjt_backend"
```

**Comment by lanroth** [comment]
Possible better solution here:
https://stackoverflow.com/questions/51024542/how-to-inject-api-server-url-when-deploying-react-frontend

**Comment by martinmphil** [comment]
Given we currently have only one back-end environment, I plan closing this issue. I'm more than happy to implement this suggested solution as soon as it becomes pertinent.

**Comment by lanroth** [comment]
We definitely need this. I'm happy to have a look at it though. Should be pretty simple

**Comment by martinmphil** [comment]
Okay.

Which two URLs would you like adding? 

I assume one of them is:
`https://lanroth.com/sjt-backend-sb/`

What's the other URL, and which one is dev and which one production? 

How about
```js
export const backend = 
  process.env.NODE_ENV === "development" ? 
  "https://lanroth.com/sjt-backend-sb/" : 
  "production_example.com/sjt";
```

**Comment by lanroth** [comment]
It will be: https://sjt-api.workbrighter.co.uk/sjt-backend-sb/

I like the idea of automatically choosing the right one based on `window.location`, e.g.:
```javascript
window.location.hostname==="sjt.workbrighter.co.uk"?
"https://sjt-api.workbrighter.co.uk/sjt-backend-sb/" :
"https://lanroth.com/sjt-backend-sb/"
```

**Comment by martinmphil** [comment]
Yeah, that's a great solution. When should we implement this code? Should we add it now or later?

**Comment by lanroth** [comment]
add it in now

**Comment by martinmphil** [comment]
Passes tests when hosted on AWS.
