### ISSUE TITLE
situation in get exam api

### ISSUE THREAD

**Issue by martinmphil** [martinmphil/judgement_tests#27]
Inside `scenario` change `question` to `situation` in GET api at `example.com/sjt-backend/exams/{examId}`
as per [wiki](https://github.com/martinmphil/judgement_tests/wiki/Naming-of-entities#scenarios)

**Comment by lanroth** [comment]
Done. Should be deployed in 2 minutes.
Could you test and close this issue if you think it's good?

**Comment by lanroth** [comment]
@martinmphil Done and deployed.
Could you test and close this issue if you think it's good?
