### ISSUE TITLE
optionText in get exam api

### ISSUE THREAD

**Issue by martinmphil** [martinmphil/judgement_tests#28]
Inside `scenario` change `answers` to `optionText` in GET api at `example.com/sjt-backend/exams/{examId}`
as per [wiki](https://github.com/martinmphil/judgement_tests/wiki/Naming-of-entities#option-text)

**Comment by lanroth** [comment]
hmm. I'm not sure I'm happy with `optionText`. I think it should be plural: `optionTexts` or `optionsText`.
Being singular makes it seem like there's only going to be one when it's many:
```json
"optionText": [ "foo", "bar", "bing" ]
"optionsText": [ "foo", "bar", "bing" ]
"optionTexts": [ "foo", "bar", "bing" ]
```
Any thoughts?

**Comment by martinmphil** [comment]
How about `judgements`? Or better still `discriminators`. Unless we can come up with a better suggestion, I think 'discriminators' might be a winner. Let me know if you like 'discriminators'  and I'll amend our [source of truth](https://github.com/martinmphil/judgement_tests/wiki/Naming-of-entities#option-text).

**Comment by lanroth** [comment]
judgements is the best we've come up with I think, so let's go with that

**Comment by martinmphil** [comment]
Updated wiki to show `judgements` as the array of possible candidate responses. Apparently 'judgements' is the common British spelling, whereas judgments without the first 'e' is used in legal contexts and North American spelling.

**Comment by lanroth** [comment]
deployed. Close this issue if you're happy @martinmphil
