### ISSUE TITLE
passing an answer to a situaton to the back end

### ISSUE THREAD

**Issue by lanroth** [martinmphil/judgement_tests#3]
I suggest we POST to:
http://example.com/candidates/answers/{examId}/{questionNum}

with the body: 
```json
{"best": "0", "worst": "1"}
```
and set the header: `candidate-token` to the token that's present in the link in the email.

You should save the token and pass it with every request.

**Comment by martinmphil** [comment]
branch fetch_2020-02-06 contains a trial for passing answer to 
example.com/candidates/answers/

https://github.com/martinmphil/judgement_tests/blob/acd847cf76e1dc7385a0324a5e5f9371825d78c6/src/App.tsx#L113

**Comment by lanroth** [comment]
That looks good to me. I'll try and get a backend up and running somewhere you can hit it in the next hour or two

**Comment by lanroth** [comment]
Backend is up but you're having problems... 
From the logs it looks like I'm not receiving a `candidate-token` (e.g. `111,` or `222`) in the request header.

**Comment by martinmphil** [comment]
Removed `mode: "no-cors"` from fetch().
201 and 204 HTTP success status response codes received when candidates answers question, so a successful trial.

**Comment by martinmphil** [comment]
Added isError state. Branch now catches error with UI message. If a candidate experiences a network error, page now shows a red coloured network error message beside the submit button that reads, "Sadly we experienced a network error. Please refresh this page, or try again later." 

https://github.com/martinmphil/judgement_tests/blob/25f0d99850031e08462e9501d78d354f316d8819/src/App.tsx#L133-L135

When merged with master branch, this addition should close this issue.
