### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by martinmphil** [martinmphil/judgement_tests#30]
Previously the SJT front-end detected a completed exam when the server returned a value for current-scenario greater than the index of the last object in the scenarios array, ie server indicates exam complete by returning current-scenario === scenarios.length

This response changed with our Spring Boot back-end.

A GET request to `/candidates/current-scenario/{examNumber}` for a completed exam now produces a 500 error with the message: "Index out of bounds for length".

**Comment by lanroth** [comment]
I've just deployed some changes so you get back something like this instead:
```json
{
  "scenarioNumber": 4,
  "totalNumberOfScenarios": 4,
  "situation": null,
  "judgements": null
}
```
Will that do it?

**Comment by lanroth** [comment]
Could you close if this fixed it for you?

**Comment by martinmphil** [comment]
Looks good from here, cheers.
