### ISSUE TITLE
get candidateID, examID and current question number

### ISSUE THREAD

**Issue by martinmphil** [martinmphil/judgement_tests#6]
App should capture candidateID and examID from URL, and then use fetch to get current question for that candidate and that exam.

**Comment by lanroth** [comment]
how should we structure the URL? How about:
`http://example.com/sjt/<examId>?idToken=<idToken>`

**Comment by martinmphil** [comment]
I imagined something like
`http://example.com/jst?candidate=123&exam=101`
But I like your example if I can understand it as
`http://example.com/jst/101?candidateId=123`
where examId is 101 and candidateId is 123

**Comment by lanroth** [comment]
I prefer the former as the form `http://example.com/sjt/<examId>` is likely what we'd be using to refer to a particular exam in a post MVP world. It's hard to explain my logic, but I assure you it's there ;-)

**Comment by martinmphil** [comment]
Took me a minute, but I think I understand your meaning.

**Comment by martinmphil** [comment]
When loading, useEffect( () => {...}, []) 
https://github.com/martinmphil/judgement_tests/blob/56f119c86f13ab4093efe38d9ea0b2c5b3bf94e6/src/App.tsx#L39
uses the url link emailed to candidate (eg example.com/jst/1?idToken=222), to identify both exam number with 
window.location.pathname
and candidate number from <idToken> with
searchParams 
see
https://github.com/martinmphil/judgement_tests/blob/56f119c86f13ab4093efe38d9ea0b2c5b3bf94e6/src/App.tsx#L41-L43
and
https://github.com/martinmphil/judgement_tests/blob/56f119c86f13ab4093efe38d9ea0b2c5b3bf94e6/src/App.tsx#L48-L49

Also, Promise.all() 
see
https://github.com/martinmphil/judgement_tests/blob/56f119c86f13ab4093efe38d9ea0b2c5b3bf94e6/src/App.tsx#L63
calls a list of all the urls needed to fetch [exam_text, current_question_nbr, candidate_name]
https://github.com/martinmphil/judgement_tests/blob/56f119c86f13ab4093efe38d9ea0b2c5b3bf94e6/src/App.tsx#L57-L61

Thus our webpage successfully gets candidateID, examID and current question number when a candidate clicks their email link.
