### ISSUE TITLE
Send invitation email to candidates

### ISSUE THREAD

**Issue by lanroth** [martinmphil/judgement_tests#7]
The front end needs to capture name and email address and pass this onto the back end.

`POST http://example.com/send_invite_email`
```json
[
    { "name": "Joe Bloggs", "email": "joe@example.com"},
    { "name": "Linus Torvalds", "email": "froopy.dood@example.com"}
]
```

The back end will create candidates, generate tokens and send emails.

**Comment by martinmphil** [comment]
I believe this process will be instigated by the Author/Assessor and hence represents a separate web app from the candidate's SJT web app. 

On a related note, if the candidate's name is unknown could we default to the email address when addressing to candidates?

**Comment by martinmphil** [comment]
For our first usability study, shall we pre-load the database with names and email addresses?

**Comment by lanroth** [comment]
Sure. Makes it simple. We'll still need a way of generating tokens and sending email invites. That all wants to happen on the back end so I'll do it. I'm part way through already

**Comment by martinmphil** [comment]
Top hole, Old Bean. Keep up the good work.
